name: TGIF

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.UWU_SECRET_KEY }}

    - name: Add SSH key to known hosts
      run: ssh-keyscan -H uwu.mov >> ~/.ssh/known_hosts

    - name: Rsync application files
      run: |
        rsync -av --exclude='.git*' --exclude='*.yml' --exclude='nginx.conf' ./ root@uwu.mov:/var/www

    - name: Copy production configurations
      run: |
        scp ./deploy/nginx.conf root@uwu.mov:/var/www/nginx.conf
        scp ./deploy/docker-compose.yml root@uwu.mov:/var/www/docker-compose.yml

    - name: Restart Docker containers
      run: ssh root@uwu.mov 'cd /var/www && docker compose down && docker compose up -d'
